on: push
name: Build and Generate Android Apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Generate Xamarin Form Android APK
        uses: fahimshahrierrasel/Xamarin-Droid-Builder@1.0.2       
  
